services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/data/db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simplecoco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-api:
    build: svc/backend
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simplecoco
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432